name: JeopardyCI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        working-directory: jeopardy-BE
        run: mvn --batch-mode --update-snapshots package
        
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        working-directory: jeopardy-BE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=JeopardyFDIBA_jeopardy
        
        
  reactCI:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3

     - name: Setup Node version 16.12.18
       uses: actions/setup-node@v3
       with:
          node-version: 16

     - name: Install dependencies
       working-directory: jeopardy-FE
       run: npm install
       

     - name: SonarCloud Scan
       uses: sonarsource/sonarcloud-github-action@master
       with:
        projectBaseDir: jeopardy-FE
        args: >
         -Dsonar.organization=fdiba
         -Dsonar.projectKey=JeopardyFDIBA_jeopardy
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
